<plugin>
    <groupId>org.jvnet.jaxb2.maven2</groupId>
    <artifactId>maven-jaxb2-plugin</artifactId>
    <version>0.14.0</version>
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <schemaLanguage>WSDL</schemaLanguage>
        <generatePackage>com.ths.ConsumingSOAPWS.wsdl</generatePackage>
        <schemas>
            <schema>
                <url>http://localhost:8080/ws/countries.wsdl</url>
            </schema>
        </schemas>
    </configuration>
</plugin>